import { COUNCIL_MEMBERS, STATUS, responseLabel } from '../shared/constants.js'

const label = (id) => COUNCIL_MEMBERS[id]?.label || id

// Did any part of a finished run not fully succeed? True if any member's Stage 1
// or Stage 2 response, or the Chairman synthesis, timed out or errored, or the
// run itself was cancelled/errored. Used to flag partial results in history.
export function runHadIssues(run) {
  if (!run) return false
  const bad = (st) => st === STATUS.TIMEOUT || st === STATUS.ERROR
  for (const bucket of [run.stage1, run.stage2]) {
    if (bucket && Object.values(bucket).some((r) => bad(r?.status))) return true
  }
  if (bad(run.stage3?.status)) return true
  return (
    run.status === STATUS.ERROR ||
    run.status === STATUS.TIMEOUT ||
    run.status === STATUS.CANCELLED
  )
}

// Human-friendly duration, e.g. 850ms → "0.9s", 74000 → "1m 14s".
export function formatDuration(ms) {
  if (ms == null || Number.isNaN(ms)) return ''
  if (ms < 1000) return `${Math.round(ms)}ms`
  const s = ms / 1000
  if (s < 60) return `${s.toFixed(1)}s`
  const m = Math.floor(s / 60)
  const rem = Math.round(s % 60)
  return `${m}m ${rem}s`
}

const dur = (ms) => (ms == null ? '' : ` [${formatDuration(ms)}]`)

// Total time across all three stages of a run. Returns null if no stage has
// been timed yet.
export function totalDuration(run) {
  const t = run?.timings
  if (!t) return null
  const parts = [t.stage1, t.stage2, t.stage3].filter((ms) => ms != null)
  if (parts.length === 0) return null
  return parts.reduce((a, b) => a + b, 0)
}

// Build a plain-text transcript of an entire council run (for copy/email).
export function formatTranscript(run) {
  if (!run) return ''
  const lines = []
  lines.push('LLM COUNCIL TRANSCRIPT')
  lines.push('======================')
  lines.push(`Query: ${run.query}`)
  if (run.finishedAt) lines.push(`Date: ${new Date(run.finishedAt).toLocaleString()}`)
  lines.push(`Members: ${run.members.map(label).join(', ')}`)
  lines.push('')

  const dumpStage = (title, bucket) => {
    lines.push(title)
    lines.push('-'.repeat(title.length))
    run.members.forEach((id, i) => {
      const r = bucket?.[id]
      if (!r) return
      lines.push(`[${label(id)} · Response ${responseLabel(i)}] (${r.status}${dur(r.ms)})`)
      lines.push(r.text || r.error || '(no output)')
      lines.push('')
    })
  }

  dumpStage('STAGE 1 — FIRST OPINIONS', run.stage1)
  dumpStage('STAGE 2 — ANONYMIZED PEER REVIEW', run.stage2)

  const s3 = run.stage3 || {}
  lines.push('STAGE 3 — CHAIRMAN SYNTHESIS')
  lines.push('----------------------------')
  lines.push(`Chairman: ${label(s3.chairman || run.chairman)} (${s3.status})`)
  lines.push(s3.text || s3.error || '(no output)')
  lines.push('')
  lines.push(
    'Note: synthesized from unverified model outputs — may be wrong; verify important claims.',
  )
  return lines.join('\n')
}

// Build a Markdown document of an entire council run (Stage 1/2 responses plus
// the Chairman's final decision) for export.
export function formatMarkdown(run) {
  if (!run) return ''
  const out = []
  out.push(`# LLM Council — ${run.query}`)
  out.push('')
  if (run.finishedAt) out.push(`- **Date:** ${new Date(run.finishedAt).toLocaleString()}`)
  out.push(`- **Members:** ${run.members.map(label).join(', ')}`)
  out.push(`- **Chairman:** ${label(run.stage3?.chairman || run.chairman)}`)
  out.push(`- **Status:** ${run.status}`)
  out.push('')

  const s3 = run.stage3 || {}
  out.push(
    `## 🏛️ Chairman Synthesis (Final Decision)${s3.ms != null ? ` _(${formatDuration(s3.ms)})_` : ''}`,
  )
  out.push('')
  out.push(s3.text || s3.error || '_No synthesis produced._')
  out.push('')

  const dumpStage = (title, bucket, stageMs) => {
    out.push(`## ${title}${stageMs != null ? ` _(${formatDuration(stageMs)})_` : ''}`)
    out.push('')
    run.members.forEach((id, i) => {
      const r = bucket?.[id]
      if (!r) return
      out.push(`### ${label(id)} — Response ${responseLabel(i)} _(${r.status}${dur(r.ms)})_`)
      out.push('')
      out.push(r.text || r.error || '_No output._')
      out.push('')
    })
  }

  dumpStage('Stage 1 — First Opinions', run.stage1, run.timings?.stage1)
  dumpStage('Stage 2 — Anonymized Peer Review', run.stage2, run.timings?.stage2)

  if (run.ranking?.ballots) {
    out.push(`## 🏅 Aggregate Peer Ranking _(${run.ranking.ballots} ballots)_`)
    out.push('')
    run.ranking.board.forEach((row, i) => {
      out.push(`${i + 1}. **${label(row.id)}** (Response ${row.label}) — ${row.points} pts`)
    })
    out.push('')
  }

  out.push('---')
  out.push(
    '_Synthesized from unverified model outputs — may be wrong or incomplete; verify important claims independently._',
  )
  out.push('_Generated by the LLM Council Chrome extension._')
  return out.join('\n')
}

// Trigger a file download from the side panel (extension page).
export function downloadText(filename, text, mime = 'text/markdown;charset=utf-8') {
  const blob = new Blob([text], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 2000)
}

// A filesystem-safe filename for a run's markdown export.
export function exportFilename(run) {
  const slug = (run.query || 'council')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48)
  const stamp = new Date(run.finishedAt || Date.now()).toISOString().slice(0, 10)
  return `llm-council-${stamp}-${slug || 'run'}.md`
}

export async function copyText(text) {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    // Fallback for environments without clipboard permission.
    try {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.position = 'fixed'
      ta.style.opacity = '0'
      document.body.appendChild(ta)
      ta.select()
      const ok = document.execCommand('copy')
      document.body.removeChild(ta)
      return ok
    } catch {
      return false
    }
  }
}

// Open the OS mail client with the results prefilled. mailto has practical
// length limits (~1900 chars), so long transcripts are truncated with a note —
// use Copy for the full text.
export function emailResults(subject, body) {
  const MAX = 1800
  let mailBody = body
  if (mailBody.length > MAX) {
    mailBody =
      mailBody.slice(0, MAX) +
      '\n\n[…truncated — use "Copy transcript" in the LLM Council panel for the full text]'
  }
  const url = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(mailBody)}`
  // A new tab hands the mailto: off to the default mail handler.
  chrome.tabs.create({ url })
}

export function relativeTime(ts) {
  if (!ts) return ''
  const diff = Date.now() - ts
  const min = Math.round(diff / 60000)
  if (min < 1) return 'just now'
  if (min < 60) return `${min}m ago`
  const hr = Math.round(min / 60)
  if (hr < 24) return `${hr}h ago`
  return new Date(ts).toLocaleDateString()
}
